# Generated by Django 4.2.7 on 2026-05-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_informationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='hazard_risk_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
